### PR TITLE
Caves cleaned up + new games mostly Zoltan's

### PR DESCRIPTION
**Pull request by renyxadarox**
First I added all known Zoltan's games, but I've found that listed below game sets are almost identical in first 30 games up to MD5:

- Auto_Dash
- Bee_Dash
- Fire_Ant_Dash
- Golden_Boulder-Who_Dares_Wins
- Invasion_Dash
- Mushroom_Dash
- Nucleal_Dash
- Pinocchio_Dash
- Robot_Dash
- Skateboard_Dash

So I decided to leave only two of them:

- Golden_Boulder-Who_Dares_Wins
- Robot_Dash
because they have more than 30 games and differ after 30th game.

I zipped all other games and put them to /caves/Scserbin_Zoltan/ folder, I hope zips won't interfere makefile.
The games won't be able to viewed from GDash, but if somehow someone will decide to play them, he (she) can unzip them and play themselves (despite the fact that they are identical to Robot_Dash and Golden_Boulder-Who_Dares_Wins).

### CODE REVIEW

**Comment by revvv** [comment]
Please avoid '-' in cave dir names. Replaced with underscore.

**Comment by renyxadarox** [comment]
Ok, are single quotes (') allowed?

**Comment by revvv** [comment]
No:

```
$ ./create_makefile.sh
$ make
 cd .. && automake-1.16 --gnu caves/Makefile
caves/Makefile.am:619: error: bad characters in variable name 'Test'testdir'
caves/Makefile.am:620: error: bad characters in variable name 'Test'test_CAVES'
caves/Makefile.am:621: error: bad characters in variable name 'Test'test_DATA'
caves/Makefile.am:621: warning: Test'test_CAVES: non-POSIX variable name
caves/Makefile.am:675: warning: Test'test_CAVES: non-POSIX variable name
/usr/share/automake-1.16/am/data.am: warning: Test'testdir: non-POSIX variable name
caves/Makefile.am:621:   while processing 'Test'test_DATA'
automake-1.16: warning: Test'test_DATA: non-POSIX variable name
make: *** [Makefile:3073: Makefile.in] Error 1
```

**Comment by renyxadarox** [comment]
[Makefile.am L.536](https://github.com/renyxadarox/gdash-export-CrLi/blob/master/caves/Makefile.am#L536)
Scserbin_Zoltan_CAVES = Scserbin_Zoltan/Arkanoid_001.gds **Scserbin_Zoltan/Atlantis/Atlantis_12.gds** ...

[Makefile.amL.540](https://github.com/renyxadarox/gdash-export-CrLi/blob/master/caves/Makefile.am#L540)
Scserbin_Zoltan_Atlantis_CAVES = **Scserbin_Zoltan/Atlantis/Atlantis_12.gds** Scserbin_Zoltan/Atlantis/Atlantis_13.gds ...

I'm not sure this is correct.

**Comment by renyxadarox** [comment]
> No:

Ok, but I'm pretty sure that single quotes are allowed in file names, right?

**Comment by revvv** [comment]
> [Makefile.am L.536](https://github.com/renyxadarox/gdash-export-CrLi/blob/master/caves/Makefile.am#L536) Scserbin_Zoltan_CAVES = Scserbin_Zoltan/Arkanoid_001.gds **Scserbin_Zoltan/Atlantis/Atlantis_12.gds** ...
> 
> [Makefile.amL.540](https://github.com/renyxadarox/gdash-export-CrLi/blob/master/caves/Makefile.am#L540) Scserbin_Zoltan_Atlantis_CAVES = **Scserbin_Zoltan/Atlantis/Atlantis_12.gds** Scserbin_Zoltan/Atlantis/Atlantis_13.gds ...
> 
> I'm not sure this is correct.

Thanks, have overseen that. Fixed. Fingers crossed. The makefile is only relevant for `make install` which I don't use. I just try to keep it compilable ;-)

**Comment by revvv** [comment]
> Ok, but I'm pretty sure that single quotes are allowed in file names, right?

Single quotes are OK in file names.

**Comment by renyxadarox** [comment]
Ok, give me 10 minutes, I'll replace "_s" with "'s", where needed.

**Comment by renyxadarox** [comment]
https://github.com/revvv/gdash-export-CrLi/pull/47 rehabilitated single qoutes in filenames

**Pull request merged**
